### ISSUE TITLE
Use PackageReference and SaveAll comand

### ISSUE THREAD

**Issue by chipushka** [0UserName/NuGetSwitcher#1]
Reproduced in Microsoft Visual Studio Community 2019 Version 16.4.2.

Steps to reproduce:
1. Use ProjectReference -  References are successfully switched to the projects 
2. Use PackageReference - References are successfully switched to the nuget\packages 
3. Choose File->SaveAll in the VS menu or Ctrl+Shift+S - some project files lose references

**Comment by 0UserName** [comment]
Unfortunately, I have no reasonable explanation for this bug. Logically, the deletion and addition of references occurs in relation to the objects in memory ([SwitchDependency](https://github.com/0UserName/NuGetSwitcher/blob/develop/NuGetSwitcher.Core/Switch/PackageSwitch.cs#L55)), after which saving is performed by calling the [Save](https://github.com/0UserName/NuGetSwitcher/blob/master/NuGetSwitcher.Helper/Entity/ProjectReference.cs#L168) function, which should write to file. And apparently it works that way, but why pressing the Save (in VS) button leads to an error, I cannot say at the moment.

**Comment by 0UserName** [comment]
@chipushka , could you double-check? This should be fixed in version 0.5.
