### ISSUE TITLE
Fails to switch from ProjectReference to PackageReference

### ISSUE THREAD

**Issue by SuperJMN** [0UserName/NuGetSwitcher#2]
It removes the project, but it doesn't add the PackageReference again.

**Comment by 0UserName** [comment]
Hi. I just saw it. Do the problem occurred while working in .NET SDK style projects? Or also for legacy projects on .NET Framework 4.6.*/4.7.* and so on. Do you use the [Condition](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019) attributes in references? Visual Studio 17 or 19?

**Comment by 0UserName** [comment]
@SuperJMN , could you double-check? This should be fixed in version 0.5.

**Comment by SuperJMN** [comment]
I'm sorry! I was too busy to deal with this checking. It seems that you've already fixed it. Thank you!
