### ISSUE TITLE
Please can you support Visual Studio 2022? I can't install extension there my friend.

### ISSUE THREAD

**Issue by softwarekamal** [0UserName/NuGetSwitcher#4]
Please my dear you do awesome work can you support Visual Studio 2022 version.
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#extensions-without-running-code

Can you edit and upgrade extension and its nuget packages please to Visual Studio 2022
Thank you dear

**Comment by 0UserName** [comment]
Greetings. Yes, I have plans to prepare to port the extension to VS 2022. I think it will be done by the end of the week.

**Comment by 0UserName** [comment]
Sorry for huge delay.. Done. Published.

---

Among other things, a CLI version is [available](https://github.com/0UserName/NuGetSwitcher/tree/develop/cli/nugetswitcher.cli) that does not depend on Visual Studio. A little later I will publish on nuget.org as global tools.

---

Let me know if you run into problems with the new version.

**Comment by softwarekamal** [comment]
Thank you much dear. Please any documentation on how to use that tool...
I try to do following:

1. Create empty WinForms Project.
2. Create ClassLibrary project. and create nuget package. and make WinForms project reference it.
3. Setup Nuget Switcher (Include Project File section from tools) to C:\deps.txt
4. deps.txt contains Folder of my solution that contains both WinForms project and ClassLibrary.
5. Note that I use PackageReference.

After Click switch to project reference nothing happened.. and vice-versa.
Please how to do it? You mentioned something about <Choose> etc... but I think this tool doesn't need that?
